import type { Metadata } from "next";
import { WalletProvider } from "@/context/WalletContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BgImage from "../assets/Bg.jpg";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LandMafia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed inset-0 -z-10">
          <Image
            src={BgImage}
            alt="Background"
            layout="fill"
            objectFit="cover"
            quality={100}
          />
          <div className="absolute inset-0  bg-opacity-70"></div>
        </div>
        <WalletProvider>{children}</WalletProvider>
      </body>
    </html>
  );
}
