import DummyImage from '../assets/Bg.jpg'
const dummyProperties = [
  {
    id: 1,
    seller: "0xD376947DF2aA98F6AfC485622F796f36a73A84bD",
    buyer: "",
    landimage: DummyImage,
    location: "Chennai",
    googlemaplink: "https://maps.google.com/?q=Chennai",
    size: "0.5 acres",
    price: "₹2,75,00,000",
    discribtion: "Premium residential plot in prime Chennai location with all approvals. Ready for construction.",
    landType: "Residential",
    saleDeed: true,
    clearanceCertificates: true,
    propertyTaxdocument: true,
    encumbranceCertificate: true,
    propertyVerification: "approved",
    registrationRequest: "pending",
    marketStatus: "available",
    transactionData: "NotCompleted",
    createdAt: "2023-05-10"
  },
  {
    id: 2,
    seller: "0xD376947DF2aA98F6AfC485622F7936a73A84bD",
    buyer: "0xD376947DF2aA98F6AfC485622F796f36a73A84bD",
        landimage: DummyImage,
    location: "Coimbatore",
    googlemaplink: "https://maps.google.com/?q=Coimbatore",
    size: "1.5 acres",
    price: "₹1,50,00,000",
    discribtion: "Commercial plot near Coimbatore IT park with high growth potential.",
    landType: "Commercial",
    saleDeed: true,
    clearanceCertificates: true,
    propertyTaxdocument: true,
    encumbranceCertificate: true,
    propertyVerification: "approved",
    registrationRequest: "approved",
    marketStatus: "nonAvailable",
    transactionData: "completed",
    createdAt: "2023-04-15"
  },
  {
    id: 3,
    seller: "0x1f9090aaE28b8a3dCeaDf281B0F12828e676c326",
    buyer: "",
        landimage: DummyImage,
    location: "Madurai",
    googlemaplink: "https://maps.google.com/?q=Madurai",
    size: "0.75 acres",
    price: "₹95,00,000",
    discribtion: "Residential plot in developing area of Madurai with good connectivity.",
    landType: "Residential",
    saleDeed: true,
    clearanceCertificates: false,
    propertyTaxdocument: true,
    encumbranceCertificate: true,
    propertyVerification: "pending",
    registrationRequest: "pending",
    marketStatus: "nonAvailable",
    transactionData: "NotCompleted",
    createdAt: "2023-06-20"
  },
  {
    id: 4,
    seller: "0xD376947DF2aA98F6AfC485622F796f36a73A84bD",
    buyer: "",
        landimage: DummyImage,
    location: "Tirunelveli",
    googlemaplink: "https://maps.google.com/?q=Tirunelveli",
    size: "2 acres",
    price: "₹1,20,00,000",
    discribtion: "Agricultural land with good water source in Tirunelveli district.",
    landType: "Agricultural",
    saleDeed: true,
    clearanceCertificates: true,
    propertyTaxdocument: false,
    encumbranceCertificate: true,
    propertyVerification: "rejected",
    registrationRequest: "pending",
    marketStatus: "nonAvailable",
    transactionData: "NotCompleted",
    createdAt: "2023-07-05"
  },
  {
    id: 5,
    seller: "0xBbBBBBBBbBBBBbBBBBbBBBBBBbBBBBbBbbBbbBB",
    buyer: "0xD376947DF2aA98F6AfC485622F796f36a73A84bD",
        landimage: DummyImage,
    location: "Hosur",
    googlemaplink: "https://maps.google.com/?q=Hosur",
    size: "3 acres",
    price: "₹3,25,00,000",
    discribtion: "Industrial plot near Bangalore border with all clearances.",
    landType: "Industrial",
    saleDeed: true,
    clearanceCertificates: true,
    propertyTaxdocument: true,
    encumbranceCertificate: true,
    propertyVerification: "approved",
    registrationRequest: "approved",
    marketStatus: "nonAvailable",
    transactionData: "completed",
    createdAt: "2023-03-12"
  },
  {
    id: 6,
    seller: "0x2E1a87C5Dc3e198F935bA8a7D5d7c5B9F8D1aB12",
    buyer: "",
        landimage: DummyImage,
    location: "Kancheepuram",
    googlemaplink: "https://maps.google.com/?q=Mahabalipuram",
    size: "1 acre",
    price: "₹4,50,00,000",
    discribtion: "Seafront commercial plot with tourism potential in Mahabalipuram.",
    landType: "Commercial",
    saleDeed: true,
    clearanceCertificates: false,
    propertyTaxdocument: false,
    encumbranceCertificate: false,
    propertyVerification: "pending",
    registrationRequest: "pending",
    marketStatus: "nonAvailable",
    transactionData: "NotCompleted",
    createdAt: "2023-08-01"
  },
  {
    id: 7,
    seller: "0xD376947DF2aA98F6AfC485622F796f36a73A84bD",
    buyer: "0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed",
    landimage: DummyImage,
    location: "Thanjavur",
    googlemaplink: "https://maps.google.com/?q=Thanjavur",
    size: "5 acres",
    price: "₹2,00,00,000",
    discribtion: "Fertile agricultural land in Thanjavur rice bowl region.",
    landType: "Agricultural",
    saleDeed: true,
    clearanceCertificates: true,
    propertyTaxdocument: true,
    encumbranceCertificate: true,
    propertyVerification: "approved",
    registrationRequest: "pending",
    marketStatus: "nonAvailable",
    transactionData: "NotCompleted",
    createdAt: "2023-02-18"
  },
  {
    id: 8,
    seller: "0xD376947DF2aA98F6AfC485622F796f36a73A84bD",
    buyer: "",
        landimage: DummyImage,
    location: "Tiruchirappalli",
    googlemaplink: "https://maps.google.com/?q=Tiruchirappalli",
    size: "0.33 acres",
    price: "₹85,00,000",
    discribtion: "Residential plot near educational institutions in Trichy.",
    landType: "Residential",
    saleDeed: true,
    clearanceCertificates: true,
    propertyTaxdocument: true,
    encumbranceCertificate: true,
    propertyVerification: "approved",
    registrationRequest: "pending",
    marketStatus: "available",
    transactionData: "NotCompleted",
    createdAt: "2023-09-10"
  }
];

export default dummyProperties;